apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-rc
  labels:
    name: tomcat-rc
spec:
  replicas: 1
  selector:
    name: tomcat-pod
    template:
      metadata:
        labels:
          name: tomcat-pod
      spec:
        # 容器定义部分
        containers:
          - name: tomcat
            image: tomcat
            ports:
              - containerPort: 8080