apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gray-release
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/elb.port: '80'
spec:
  rules:
    - host: gray.microfoolish.com
      http:
        paths:
          - path: '/'
            backend:
              serviceName: old
              servicePort: 80