apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    # 启用Canary
    nginx.ingress.kubernetes.io/canary: "true"
    # Cookie中包含user_from_bj的请求转发到Canary Ingress
    nginx.ingress.kubernetes.io/canary-by-cookie: "user_from_bj"
    kubernetes.io/elb.port: '80'
spec:
  rules:
    - host: gray.microfoolish.com
      http:
        paths:
          - path: '/'
            backend:
              # 指定后端服务为new-nginx
              serviceName: new-nginx
              servicePort: 80