apiVersion: apps/v1
kind: Deployment
metadata:
  name: new
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new
    spec:
      containers:
        - image: swr.cn-east-3.myhuaweicloud.com/hwfstaff_pub_cbuinfo/nginx:new    # 容器使用的镜像为：nginx:new
          name: new
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      imagePullSecrets:
        - name: default-secret

---
apiVersion: v1
kind: Service
metadata:
  name: new
spec:
  selector:
    app: new
  ports:
    - name: new
      targetPort: 80
      port: 8080
      protocol: TCP
  type: NodePort