apiVersion: apps/v1
kind: Deployment
metadata:
  name: old
spec:
  replicas: 2
  selector:
    matchLabels:
      app: old
  template:
    metadata:
      labels:
        app: old
    spec:
      containers:
        - image: swr.cn-east-3.myhuaweicloud.com/hwfstaff_pub_cbuinfo/nginx:old
          name: old
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
      imagePullSecrets:
        - name: default-secret

---
apiVersion: v1
kind: Service
metadata:
  name: old
spec:
  selector:
    app: old
  ports:
    - name: old
      targetPort: 80
      port: 8080
      protocol: TCP
  type: NodePort